apiVersion: apps/v1
kind: Deployment
metadata:
  name: despachos
  namespace: innovatech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: despachos
  template:
    metadata:
      labels:
        app: despachos
    spec:
      containers:
        - name: despachos
          image: 308769698189.dkr.ecr.us-east-1.amazonaws.com/backend-innovatech:despachos
          ports:
            - containerPort: 8085
          env:
            - name: SERVER_PORT
              value: "8085"

            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: SPRING_DATASOURCE_PASSWORD

            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "3"

            - name: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
              value: "1"

            - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
              value: "30000"

            - name: SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT
              value: "120000"

            - name: SPRING_DATASOURCE_HIKARI_MAX_LIFETIME
              value: "300000"

            - name: SPRING_DATASOURCE_HIKARI_KEEPALIVE_TIME
              value: "60000"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: despachos-service
  namespace: innovatech
spec:
  selector:
    app: despachos
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP