apiVersion: apps/v1
kind: Deployment
metadata:
  name: despachos
  namespace: innovatech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: despachos
  template:
    metadata:
      labels:
        app: despachos
    spec:
      containers:
        - name: despachos
          image: 308769698189.dkr.ecr.us-east-1.amazonaws.com/backend-innovatech/innovatech-despachos:latest
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: despachos-service
  namespace: innovatech
spec:
  selector:
    app: despachos
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP