apiVersion: apps/v1
kind: Deployment
metadata:
  name: ventas
  namespace: innovatech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ventas
  template:
    metadata:
      labels:
        app: ventas
    spec:
      containers:
        - name: ventas
          image: 308769698189.dkr.ecr.us-east-1.amazonaws.com/backend-innovatech:ventas
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: ventas-service
  namespace: innovatech
spec:
  selector:
    app: ventas
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP